export const ERROR = 'ERROR';

export const FETCH_BEGIN = 'FETCH_BEGIN';
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const FETCH_DETAILS_BEGIN = 'FETCH_DETAILS_BEGIN';
export const FETCH_DETAILS_SUCCESS = 'FETCH_DETAILS_SUCCESS';
export const FETCH_DETAILS_FAILURE = 'FETCH_DETAILS_FAILURE';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const FETCH_SEARCH_NOTFOUND = 'FETCH_SEARCH_NOTFOUND';